### ISSUE TITLE
Recording as Mirror Mode

### ISSUE THREAD

**Issue by CherryChann** [collab-project/videojs-record#160]
I want to record the video as mirror mode and I want to know if it has any options i can do about it.

**Comment by thijstriemstra** [comment]
@CherryChann you can mirror the video element during preview/recording. Add the following CSS (taken from https://stackoverflow.com/a/14455993):

```css
video
{
    transform: rotateY(180deg);
    -webkit-transform:rotateY(180deg); /* Safari and Chrome */
    -moz-transform:rotateY(180deg); /* Firefox */
}
```
