### ISSUE TITLE
Ability to change label of record indicator

### ISSUE THREAD

**Issue by yaguiman72** [collab-project/videojs-record#336]
Hi,
  I've used the Angular tutorial to create the component and it worked like a charm but now we would like to customize the REC text and icon that it is shown on the upper right corner.
 I've added the class in `videojs.record.component.css` file like:

```css
.vjs-record.video-js .vjs-control.vjs-record-indicator:before {
    content: "GRABANDO";
    color: white;
    position: absolute;
    left: -2.7em;
    font-family: "Helvetica", sans-serif;
    animation-name: pulsetext;
    animation-duration: 5s;
    animation-iteration-count: infinite;
    top: -0.1em;
    font-size: 0.8em;
    opacity: 1;
    transition: opacity .5s .2s;
}
```
but it takes the style from `node_modules/videojs-record/dist/css`...

How can I customize the component using Angular?. 

I'll appreciate any help on this.

Thanks and regards,
Martin
